### ISSUE TITLE
Excluding/Adding metrics in lambda's graphs

### ISSUE THREAD

**Issue by souryaly** [cdklabs/cdk-monitoring-constructs#191] opened 2022-07-07 19:12 UTC
### Feature scope

Lambda

### Describe your suggested feature

Provisioned Concurrency Spillover count is included in lambda's invocation graph even though it is unused by our BoxerTicketingService so we would like to remove it. 

Also in the latency graph, we would like to add TM99 metric and remove the P90 and P50 metrics

The ask is the ability to remove/add metrics to lambda's graphs (specifically "Invocations" and "Latency" graphs)

**Comment by echeung-amzn** [comment] 2022-07-13 21:18
Duplicate of #66

**Closed by echeung-amzn** 2022-07-13 21:18 UTC
Labels: feature-request
