### ISSUE TITLE
monitoringAspect support all monitoring services

### ISSUE THREAD

**Issue by adminy** [cdklabs/cdk-monitoring-constructs#561] opened 2024-08-20 16:46 UTC
### Feature scope

Fargate

### Describe your suggested feature

There are a couple of services not aspected, i.e. `monitorFargateService`.
Its nice to have one api call cover everything with common patterns to all services, its just strange to use a combination of monitoringAspect as well as specific services. Would be nice to have all services aspectable.

**Comment by echeung-amzn** [comment] 2024-08-20 18:31
Duplicate of #41

**Closed by echeung-amzn** 2024-08-20 18:31 UTC
Labels: feature-request
